[versions]
# plugins
android = "8.10.1"
kotlin = "2.1.21"

# ziti projects
ziti-tunnel-sdk = "v1.6.0"

# 3rd part deps
kotlinx-serialization-json = "1.8.1"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
lifecycle-extensions = "2.2.0"
material = "1.12.0"
lifecycle = "2.9.1"
coroutines = "1.10.2"
zxing-android-embedded = "4.3.0"
datastore = "1.1.7"
fragment = "1.8.7"
activity-compose = "1.10.1"
compose-bom = "2025.06.01"

# test deps
junit = "4.13.2"
espresso-core = "3.6.1"
core-ktx-version = "1.16.0"
junit-version = "1.2.1"

[libraries]
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
datastore-prefs = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
junit = { module = "junit:junit", version.ref = "junit" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
material = { module = "com.google.android.material:material", version.ref = "material" }
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
material3 = { group = "androidx.compose.material3", name = "material3" }

zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxing-android-embedded" }

core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx-version" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }

[plugins]
android-app = { id = "com.android.application", version.ref = "android" }
android-lib = { id = "com.android.library", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[bundles]

