[versions]
# plugins
android = "8.1.0"
kotlin = "1.9.10"
dokka = "1.8.20"
nexus = "1.3.0"
semver-git = "2.3.7"

# 3rd part deps
slf4j-android = "2.0.7-0"
appcompat = "1.6.1"
constraintlayout = "2.1.4"
lifecycle-extensions = "2.2.0"
material = "1.9.0"
pcap4j = "1.8.2"
lifecycle = "2.6.1"
coroutines = "1.7.3"
core-ktx = "1.10.1"
lazysodium-android = "5.1.0"
jna = "5.13.0"
retrofit = "2.9.0"
zxing-android-embedded = "4.3.0"

# ziti
ziti-core = "0.25.1"
ziti-android = "0.30.0"

# test deps
hamcrest-core = "2.2"
junit = "4.13.2"
test = "1.5.0"
espresso-core = "3.5.1"

[libraries]
slf4j-android = { module = "uk.uuid.slf4j:slf4j-android", version.ref = "slf4j-android" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
hamcrest-core = { module = "org.hamcrest:hamcrest-core", version.ref = "hamcrest-core" }
junit = { module = "junit:junit", version.ref = "junit" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
material = { module = "com.google.android.material:material", version.ref = "material" }
pcap4j-core = { module = "org.pcap4j:pcap4j-core", version.ref = "pcap4j" }
pcap4j-packetfactory-static = { module = "org.pcap4j:pcap4j-packetfactory-static", version.ref = "pcap4j" }
ziti-core = { group = "org.openziti", name="ziti", version.ref="ziti-core" }
ziti-android = { group = "org.openziti", name="ziti-android", version.ref="ziti-android"}
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

test-runner = { group = "androidx.test", name = "runner", version.ref="test" }
test-rules = { group = "androidx.test", name = "rules", version.ref="test" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxing-android-embedded" }

jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }

[plugins]
android-app = { id = "com.android.application", version.ref = "android" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus" }
semver-git = { id = "io.wusa.semver-git-plugin", version.ref = "semver-git" }

[bundles]

